name: Multi-Repo Github Actions Unit Testing

on:
  workflow_dispatch:

jobs:
  trigger-other-repo-workflows:
    runs-on: ubuntu-latest
    # Trigger workflows in other repos
    steps:
    - name: Trigger workflow in hw-ui-service
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GH_ACTIONS_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/thunderbirdgit/hw-ui-service/dispatches \
        -d '{"event_type":"ci-unittest"} "client_payload": {"ref": "refs/heads/thunderbirdgit-patch-2"}}'
