name: Determine Branch Name

on:
  workflow_call:
    outputs:
      branch_name:
        description: "The name of the branch"
        value: ${{ jobs.determine-branch.outputs.branch_name }}

jobs:  
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - name: Get Branch Name
        id: get_branch
        run: |
          ## Get source branch name for push event
          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "repository_dispatch" ]]; then
            branch_name=${GITHUB_REF#refs/heads/}
            echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          ## Get head branch name for pull_request event
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch_name=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          fi

      - name: Print Final Branch Name
        run: |          
          echo "Branch Name: ${{ steps.get_branch.outputs.branch_name }}"
