name: Build Nodejs CI Docker Image and publish to ECR

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string      
      short_sha:
        required: true
        type: string
      branch_name:
        required: true
        type: string      
env:
  ECR_REPO: "050752621859.dkr.ecr.us-west-2.amazonaws.com"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Print Inputs
      run: |
        echo "Service Name: ${{ inputs.service_name }}"
        echo "Git SHA: ${{ inputs.short_sha }}"
        echo "Branch Name: ${{ inputs.branch_name }}"    
    
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build -t "${{ inputs.service_name }}" .
      
    - name: Tag the Docker image
      run: docker tag "${{ inputs.service_name }}":latest "$ECR_REPO/${{ inputs.service_name }}":latest

    - name: Check AWS Credentials
      run: |
        echo "AWS Access Key ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        echo "AWS Region: "us-west-2"
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-west-2"
        
    
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ env.ECR_REPO }}
    
    - name: Publish the Docker image to ECR repo
      run: docker push "$ECR_REPO/${{ inputs.service_name }}:latest"
