name: Build Nodejs CI Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string      
      #short_sha:
      #  required: true
      #  type: string
      #branch_name:
      #  required: true
      #  type: string      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Print Inputs
      run: |
        echo "Input 1: ${{ inputs.service_name }}"        
    - uses: actions/checkout@v4
    - name: Show Short Git SHA
      run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t "${{ inputs.service_name }}-${{ env.short_sha }}-${{ github.head_ref }}" .
