name: Build Nodejs CI Docker Image and publish to ECR

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string      
      short_sha:
        required: true
        type: string
      branch_name:
        required: true
        type: string      
env:
  ECR_REPO: "050752621859.dkr.ecr.us-west-2.amazonaws.com"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Print Inputs
      run: |
        echo "Service Name: ${{ inputs.service_name }}"
        echo "Git SHA: ${{ inputs.short_sha }}"
        echo "Branch Name: ${{ inputs.branch_name }}"    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t "${{ inputs.service_name }}" .
    - name: Tag the Docker image
      run: docker tag "${{ inputs.service_name }}":latest "$ECR_REPO/${{ inputs.service_name }}":latest
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1      
      with:
        registries: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Publish the Docker image to ECR repo
      run: docker push "$ECR_REPO/${{ inputs.service_name }}":latest
